import Head from "next/head";

import { useState } from "react";

import classes from "../styles/Home.module.css";

import Navbar from "../Components/Navbar/Navbar";

import Header from "../Components/Header/Header";

import Contents from "../Components/Contents/Contents";

import ContentList from "../Components/Contents/ContentList";

import CardItem from "../Components/BlogContent/CardItem";

import Modal from "../Components/Signin/Modal";

import axios from 'axios'


export const getServerSideProps = async () => {

  

      const blogResponse = await  axios.get(`http://localhost:8080/api/blogs`)

      const moduleResponse = await axios.get(`http://localhost:8080/api/contents`)

         console.log("from home ssr response : ", blogResponse , " module: " , moduleResponse);

         const blogData = blogResponse.data

         const moduleData = moduleResponse.data

  return {

    props: {blogData,moduleData}

  }

}

export default function Home({blogData, moduleData}) {


  const [ modal, setShowModal]  = useState(false)

  const handleModal = ()=> setShowModal(true);


  const listOfBlogItems = ()=> blogData.map((blog,index)=>{

    return(

      <CardItem title={blog.title} userName={blog.postedBy} imageUrl={blog.image.url} content={blog.content} key={blog.createdAt} />

    )


  })



  const listOfContents = () => moduleData.map((module,index)=>{

    return(

          <ContentList title={module.title} link={module.slug} key={module.createdAt}/>

    )
  })
 


  return (
    <div className={classes.container}>

      <Head>
        <title>Cyber Defense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header handleModal={handleModal}/>
      <Modal show={modal} onClose={()=> setShowModal(false)}/>
      

      <Navbar />

      <div className={classes.main__wrappper}>

        <Contents>
            {listOfContents()}
        </Contents>

        <main className={classes.main__container__wrapper}>

          {listOfBlogItems()}
                        
         </main>
        
      </div>
      
    </div>
  );
}
