import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../Components/Navbar/Navbar'

import Header from '../Components/Header/Header'
import Contents from '../Components/Contents/Contents'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cyber Defense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <Header/>
      <Navbar/>
      <Contents/>
      <main className={styles.main}>
     
        <h1 className={styles.title}>
         
        </h1>
      </main>
       
    </div>
  )
}
