import Head from "next/head";

import classes from "../styles/Home.module.css";

import Navbar from "../Components/Navbar/Navbar";

import Header from "../Components/Header/Header";
import Contents from "../Components/Contents/Contents";

import MainContainer from "../Components/BlogContent/MainContainer";

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Cyber Defense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <div className={classes.main__wrappper}>
        <Contents />
        <MainContainer />
      </div>
    </div>
  );
}
